### ISSUE TITLE
Typo in class Preproccesing

### ISSUE THREAD

**Issue by AngelBerihuete** [franciscopalmeromoya/biosc#2]
Dear Francisco. Playing with your code I've noticed a typo in class definition biosc/preprocessing:

```python
class Preproccesing:
    """Data cleaning"""
    def __init__(self, filename : str, nStars : int = None, sortPho : bool = False):
        """Read dataset file and sample nStars from the generated dataframe
```

maybe is better to write `Preprocessing` instead of `Preproccesing`. This is why example in README.md does not work:

```python
from biosc.preprocessing import Preprocessing
```

**Comment by franciscopalmeromoya** [comment]
Dear Angel, thanks for spotting the typo. @luisgonzalezramirez also saw the same (cordobesian) typo, and I forgot to push the correction to origin after fixing it. It's done now!
